#!/usr/bin/env bash

# Script para criar bucket no S3, com um nome personalizado.

# Verifica se o nome do bucket foi passado como argumento.
if [ -z "$1" ]; then
  echo "Bucket name not provided."
  exit 1
fi

# Atribui o nome do bucket passado como argumento à variável BUCKET_NAME.
BUCKET_NAME="$1"

# Verifica se foi passado um segundo argumento, que é um argumento adicional ao comando delete-bucket.
if [ -n "$2" ]; then
  ADDITIONAL_ARGUMENT="$2"
fi

# Define a região do bucket.
AWS_REGION=$(aws ec2 describe-availability-zones \
  --output text \
  --query 'AvailabilityZones[0].[RegionName]')

# Verifica se a região definida no CLI é diferente da região definida no script acima.
if [ "$AWS_REGION" != "$(aws configure get region)" ] \
  && [ -n "$(aws configure get region)" ]; then
    AWS_REGION="$(aws configure get region)"
fi

# Se o AWS_REGION estiver vazio, usa como default a região us-east-1 .
if [ -z "$AWS_REGION" ]; then
  AWS_REGION="us-east-1"
fi

# Exclui o bucket. Se a região for us-east-1, não é necessário passar o parâmetro --region.
if [ "$AWS_REGION" = "us-east-1" ]; then
  aws s3 rb \
    s3://"$BUCKET_NAME" \
    "$ADDITIONAL_ARGUMENT"
else
  aws s3 rb \
    s3://"$BUCKET_NAME" \
    --region "$AWS_REGION" \
    "$ADDITIONAL_ARGUMENT"
fi

# Se o bucket foi excluído com sucesso, exibe o nome do bucket excluído.
if [ $? -eq 0 ]; then
  echo "Bucket deleted: $BUCKET_NAME in region $AWS_REGION"
fi